// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:sleek_circular_slider/sleek_circular_slider.dart';

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // No app-level setup declared in tour/app.tour.yaml.
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('radio_player', 10000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/radio');
  }),
  TourStep('radio_sleep_timer', 6000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/radio/timer');
  }),
  TourStep('radio_timer_set', 4000, true, (WidgetTester tester, StackRouter router) async {
    // The vinyl timer page (templates/pages/radio/timer_page.dart)
    // replaced the old preset ChoiceChips with a SleekCircularSlider
    // dial, so the step drags the dial a little to put a non-zero
    // countdown on screen before the capture. Tolerant: if the dial is
    // not on screen, the timer page is simply captured as-is.
    final Finder dial = find.byType(SleekCircularSlider);
    if (dial.evaluate().isNotEmpty) {
      await tester.drag(dial.first, const Offset(70, 0),
          warnIfMissed: false);
      await tester.pumpAndSettle(const Duration(milliseconds: 500));
    }
  }),
];
